Implement all REST API endpoints (GDEV-1584)
ghga-de/work-package-service pull request #4
Opened 2023-04-06 19:13 UTC by Cito

This PR implements all specified REST API endpoints.

The capability to check which files belong to a given dataset is still missing.

2023-04-11 16:00 UTC, KerstenBreuer requested changes
Just some minor suggestions. Please ignore the PMO flagged comments if you don't feel like addressing them right away.

2023-04-11 16:00 UTC, KerstenBreuer commented on wps/core/repository.py
> +          with what is stored in the work package
PMO

2023-04-12 06:42 UTC, Cito commented on wps/adapters/inbound/fastapi_/routes.py
> +    )
Made the names more specific in f63e06f.

2023-04-12 06:47 UTC, Cito commented on wps/config.py
> +    work_package_signing_key = SecretStr("{}")
Changed in 7644665.

2023-04-12 06:50 UTC, Cito commented on wps/core/repository.py
> +        token: Optional[str] = None,
Yes, the token is required in the route, i.e. you get a "forbidden" error when not passing a token in the header. The repository method is more common and does not require it, but checks the hash it if it is passed.

2023-04-12 07:05 UTC, Cito commented on wps/core/repository.py
> +          with what is stored in the work package
Changed in 997eb9e.

2023-04-12 07:05 UTC, Cito commented on wps/core/repository.py
> +    ) -> Optional[str]:
Changed in 997eb9e.

2023-04-12 14:58 UTC, KerstenBreuer approved these changes

2023-04-12 15:01 UTC, merged